-- AlterTable
ALTER TABLE "Time" ALTER COLUMN "monday" SET DATA TYPE TIMETZ,
ALTER COLUMN "tuesday" SET DATA TYPE TIMETZ,
ALTER COLUMN "wednesday" SET DATA TYPE TIMETZ,
ALTER COLUMN "thursday" SET DATA TYPE TIMETZ,
ALTER COLUMN "friday" SET DATA TYPE TIMETZ,
ALTER COLUMN "saturday" SET DATA TYPE TIMETZ,
ALTER COLUMN "sunday" SET DATA TYPE TIMETZ;
